version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "8002:8002"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_PAGE_IDS=${NOTION_PAGE_IDS}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - LLM_HOST=${LLM_HOST}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - QDRANT_URL=qdrant:6333  # Corrected the service name
    networks:
      - my_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
