version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - my_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
